linters:
  eslint:
    config: '.eslintrc'
  stylelint:
    config: '.stylelintrc'

files:
  # Ignore the files that match these glob patterns.
  # Be careful to quote strings as `*` has special
  # meaning in YAML files.
  ignore:
    - 'node_modules'

branches:
  # Ignore pull requests to the named branches
  ignore:
    - 'wip'
    - 'feedback'

review:
  # Don't use 'failure' build status when
  # a pull request contains style errors.
  fail_on_comments: false

  fixers:
    enable: true
